language: bash

install:
    - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - mkdir -p ~/.config/pearl
    - echo "alias q='exit'" > ~/.config/pearl/sshrc

script:
    - ./bin/ssh-pearl -v -o "StrictHostKeyChecking no" localhost -- q
    - ./bin/ssh-pearl -v -o "StrictHostKeyChecking no" localhost -- ls -lh
